### ISSUE TITLE
Missing normal motion commands

### ISSUE THREAD

**Issue by kiryph** [inkdropapp/inkdrop-vim#1]
I miss 
- `0`
- `ge`
- `gE`
- `%` matching bracket
- some auto marks would also be great such as `''` (last location) and `'.` (last edit).

And I like following way of entering insert mode:
- `gi` enter insert mode where I left

Obviously there are many more, but these were those which I instantaneously noted.

**Comment by craftzdog** [comment]
Hi, thank for the feedback!

Some keymaps are missing as you pointed out.
It is my fault that I forgot to add them to the keymaps.
I'll work on it.

I guess it can't support `gi` because the vim support is based on [CodeMirror implementation](https://codemirror.net/demo/vim.html) and it doesn't support it.

**Comment by craftzdog** [comment]
`0` is mapped to `|`:

https://github.com/inkdropapp/inkdrop-vim/blob/master/keymaps/vim.json#L30

**Comment by craftzdog** [comment]
vim@0.2.3 is out. `ge` and `gE` have been supported.
`%` matching bracket will be supported in the next release of Inkdrop.

Thanks!

**Comment by ShoMasegi** [comment]
I miss

- `ciw` : delete a word on cursor, and enter insert mode.

Please support this command.
