### ISSUE TITLE
pipe binding instead of zero

### ISSUE THREAD

**Issue by gregwebs** [inkdropapp/inkdrop-vim#5]
I don't understand why this is different then my normal vi keys, but I think it will be useful to at least have this issue to document how to change it.

```
➜  cat ~/.config/inkdrop/keymap.cson
{
  ".CodeMirror.vim-mode:not(.insert-mode):not(.key-buffering) textarea": {
      "0": "vim-mode:move-to-beginning-of-line"
  }
}
```

**Comment by craftzdog** [comment]
I believe that "0" in normal mode has a conflict with other keymap, so I dropped it. But I will look into it.
Here is [the documentation about how to customize keymaps](https://github.com/inkdropapp/inkdrop-vim#key-customizations).
Since there are too many things to document for customization, basically please ask me if you don't understand how to change them.
